### ISSUE TITLE
Incompatibility with Cameras Without "Camera" In their Title/Name When System Language is English

### ISSUE THREAD

**Issue by jandreaucodes** [x74353/KeyJerk-Reactions#6]
I installed the DMG and gave it the accessibility permissions it needed, but the reaction isn't triggering.

When I trigger one of them, I see the menubar item get selected and a reaction get clicked, but the effect doesn't happen in my video feed. If I directly click on the reastion in the video app in my menubar, it works.

![Brave Browser-QnGovLC0-001849](https://github.com/user-attachments/assets/2d81fc96-ecc1-4608-9318-c2a7b90a7e8d)

In the gif, you can see the video icon flash for a moment. 

Any thoughts? I'd love to incorporate this into my Stream deck.

**Comment by x74353** [comment]
Hi @jandreaucodes, it's hard to know exactly what's happening based on your screen recording alone as there does not appear to be an app accessing your Mac's camera when you made the recording. However, I suspect the issue is the ARK (Audio Routing Kit) system extension from Rogue Amoeba. Do you have SourceSource installed? If so, you can try quitting SoundSource, launch an app that accesses your Mac's camera, and see if KeyJerk Reactions successfully applies Reactions. ARK/ACE is specifically called out in the Known Issues/Incompatibilities section of the README.md file.

The problem is that when the Audio and Video Controls menu bar item is activated (clicked), ARK/ACE appears as the first item in the horizontal list of apps accessing your Mac's microphone/camera/screen. Since ARK isn't accessing your Mac's camera, the Reactions section isn't present when KeyJerk Reactions tries to trigger the Reaction.

I've been using SoundSource for a few years and really like it, so hopefully I can develop a solution. As of right now, I've uninstalled SourceSource on all my Macs in favor or using KeyJerk Reactions. To fix the incompatibility, I imagine one of two things will need to happen:

1. KeyJerk Reactions will need to detect the presence of ARK and click over to the next app in the horizontal list along the top of the Audio and Video Controls menu bar item's "window"/menu. This solution assumes the next app/service in the list is the one you want to apply the Reaction in, which could be an incorrect assumption. 

2. I will have to develop some sort of user-definable "priority list " of apps when applying a Reaction. Example: if Zoom is running/accessing your camera, always try to target Zoom first, else if Zoom is not running, target some other app, etc.

Or, perhaps there's another way to fix this that I'm just not considering yet. 🙂

![ScreenShot 2024-11-13 at 18 45 53](https://github.com/user-attachments/assets/6030eb61-73f0-4b8f-ba3d-6fcef83a8378)

**Comment by jandreaucodes** [comment]
Thanks for the response @x74353 !

I didn't see the note about SoundSource in the README. But, that said, I just tried quitting it and am seeing the same behavior. When in a Zoom, I click on the menu bar, select a reaction and it selects the camera icon, tries to navigate down the menu and then fails.

This is my video menubar item with SoundSource exited:

![Brave Browser-Pq1c9O0y-001855@2x](https://github.com/user-attachments/assets/4c73be68-2682-4d52-99b0-75702ff37c46)

Any other thoughts I can try?

**Comment by x74353** [comment]
@jandreaucodes Ahh... ok, I believe I know what the issue is. Thanks for the helpful screen shot. It looks like you have an external camera (MX Brio). KeyJerk Reactions is looking for something with "Camera" in its title/name. All of the UI elements are nested, so KeyJerk Reactions moves programmatically through each section, looking for the right elements.

This issue (UI element "names" not being found) is accounted for in the non-English setup, but since your system language is English, you aren't being prompted to define the "name" of your camera. I'll need to build a function that detects this condition and prompts you to define the camera name.

To test (if your Mac has a built-in FaceTime camera) you can try disconnecting the MX Brio and using the FaceTime camera to confirm. I'll try to do some work on this this week/weekend and post an update (code signed/notarized) for you to test, if you're willing to.

**Comment by x74353** [comment]
@jandreaucodes Unfortunately, I haven't had time to do any work on this as of yet. However, I was thinking last night about the problem and realized there may already be a solution built into the current version of KeyJerk Reactions. 

Could you try quitting the app, running the following command in Terminal, and relaunching?:
`defaults write com.if.KeyJerk-Reactions.plist Camera "MX Brio"`

**Comment by jandreaucodes** [comment]
No dice, unfortunately. Even after setting the camera to MX Brio, it's the same behavior where the camera selector in the menu bar fires, but then it doesn't seem to select the right reaction from the dropdown.

**Comment by x74353** [comment]
@jandreaucodes I apologize, the key name was incorrect. Please try again with the following Terminal command:
`defaults write com.if.KeyJerk-Reactions.plist CameraTitle "MX Brio" `

**Comment by jandreaucodes** [comment]
That did the trick.

Now I just need to weigh if I want to use this more than I want to use SoundSource. :-D

**Comment by x74353** [comment]
As a Sound Source user myself, I want to find a solution so hopefully there is one. I'll create an issue for tracking that in the near future, or feel free to create one if you have time. 

I'll also build something into Settings or elsewhere so folks don't have to mess around with `defaults write` if they have an external camera. Will have to test what happens when you have multiple cameras connected too I suppose. Think I will keep this issue open for the time being. Thanks for reporting.

**Comment by x74353** [comment]
@jandreaucodes As a workaround, when SoundSource/ARK is running, I _believe_ you should be able to select Zoom or whatever app you're using in the Audio and Video Controls window and your selection will be retained for some time. Have not done a lot of testing on this, but try:

• Launch Zoom/other app and turn on your camera feed
• Click the Audio and Video Controls menu bar item
• Select Zoom/other app in the horizontal scroll area/list at the top of the Audio and Video Controls window
• Use KeyJerk Reations normally

At some point, (perhaps when you quit Zoom (or other app) / end your meeting / turn off the camera feed) it may revert to having ARK selected.

**Comment by jandreaucodes** [comment]
That does look like it works!

Now I just need to find time to create keyboard shortcuts for all of them and map them to my Stream Deck. :-D

**Comment by x74353** [comment]
@jandreaucodes. This issue should be resolved with the 2.1 release. You can now define your camera's name in settings. I've also introduced App Priorities in 2.1, which should resolve the issue with the ARK (Audio Routing Kit) system extension from Rogue Amoeba.

You can read about both new features here:
https://x74353.github.io/KeyJerk-Reactions/Documentation/Settings.html

And download the 2.1 release here (maybe someday I'll add over-the-air updates):
https://github.com/x74353/KeyJerk-Reactions/raw/main/DMG/KeyJerk%20Reactions.dmg

**Comment by x74353** [comment]
@jandreaucodes That's odd. Do let me know if the issue persists. You could try the following:

• Launch Activity Monitor from /Application/Utilities and check if KeyJerk Reactions is running.
• Perform a settings reset with the following Terminal command:
`defaults delete com.if.KeyJerk-Reactions.plist`

Note: you may need to also run this command in Terminal to quit KeyJerk Reactions if you can't access it via the menu bar:
`killall "KeyJerk Reactions"`

If none of that works, there is probably some unhandled error in the code that is stopping the execution prior to the creation of the menu bar item.

**Comment by jandreaucodes** [comment]
Still no luck, unfortunately.

I looked in Console and don't see anything being logged around an error or crash. But when I launch 2.1, something's preventing it from showing up in my menu bar entirely.
